#ifndef SRC_COMMUNICATION_H_
#define SRC_COMMUNICATION_H_

#define SENDFILESSIZE 0
#define SENDFILESCONT 1
#define SENDAFFINSIZE 2
#define SENDAFFINCONT 3
#define SENDRECEPTORS 4
#define SENDNMTHREADS 5

#endif /* ifndef SRC_COMMUNICATION_H_ */
